### PR TITLE
Task 4: integration with database

### PR DESCRIPTION
**Pull request by ambroseus**
Linked PR: https://github.com/ambroseus/shop-react-redux-cloudfront/pull/3
SPA: https://ambroseus-store.esam-dev.link
Admin page: https://ambroseus-store.esam-dev.link/admin/products
Allowed to CREATE/MANAGE/DELETE products
Screenshot from 2022-07-24 23-23-53

Swagger UI: https://kuc6so4utb.execute-api.us-east-1.amazonaws.com/swagger
Swagger JSON: https://kuc6so4utb.execute-api.us-east-1.amazonaws.com/swagger.json

- [x] endpoint **health_check** GET https://x5drzi6hfj.execute-api.us-east-1.amazonaws.com/dev/health-check
- [x] endpoint **get_products_list** GET https://x5drzi6hfj.execute-api.us-east-1.amazonaws.com/dev/products
- [x] endpoint **get_product_by_id** GET https://x5drzi6hfj.execute-api.us-east-1.amazonaws.com/dev/products/b7061da3-4ca2-40d6-8831-7c31d710a68d
- [x] endpoint **create_product** POST https://x5drzi6hfj.execute-api.us-east-1.amazonaws.com/dev/products
- [x] endpoint **update_product** PUT https://x5drzi6hfj.execute-api.us-east-1.amazonaws.com/dev/products
- [x] endpoint **deleteProduct** DELETE https://x5drzi6hfj.execute-api.us-east-1.amazonaws.com/dev/products/[productId]

- [x] Create tables, Write SQL script to fill tables with test examples (/sql/init-tables.sql)

- [x] Lambda functions returns error 400 status code if product data is invalid
- [x] All lambdas return error 500 status code on any error 
- [x] All lambdas do console.log for each incoming requests and their arguments
- [x] Transaction based create/update/delete product

### CODE REVIEW

**Comment by cetrix13** [comment]
@ambroseus Something is wrong with a post request to create a product. Here is an error in Postman:

image

**Comment by ambroseus** [comment]
@cetrix13  mm.. let me check.. meanwhile Product creation via SPA works as expected :)

**Comment by ambroseus** [comment]
@cetrix13 
checked with postman:
Screenshot from 2022-07-25 11-57-14
Screenshot from 2022-07-25 11-57-39

**Comment by ambroseus** [comment]
maybe you forgot to add header
Screenshot from 2022-07-25 11-59-30

yours:
Screenshot from 2022-07-25 12-00-02

mine:
Screenshot from 2022-07-25 12-04-26

**Comment by ambroseus** [comment]
btw, interesting case :) maybe need to add CORS rule to accept only `Content-type: application/json` header

**Comment by xdMus** [comment]
Found 1 popular bug with `PUT` request - if we send wrong uuid it will respond anyway with status code `200`
Should it be fixed in for this service?

image

**Comment by xdMus** [comment]
And something wrong with your SWAGGER. It always return 404 error
image

**Comment by ambroseus** [comment]
@xdMus  Hi, please use correct urls for Swagger (they are different from api base url):

Swagger UI: https://kuc6so4utb.execute-api.us-east-1.amazonaws.com/swagger
Swagger JSON: https://kuc6so4utb.execute-api.us-east-1.amazonaws.com/swagger.json

Screenshot from 2022-07-26 13-40-34

**Comment by ambroseus** [comment]
> Found 1 popular bug with `PUT` request - if we send wrong uuid it will respond anyway with status code `200` Should it be fixed in for this service?
> 
> image

@xdMus  yep)) you are absolutely right! I'll add the fix with validation ASAP (today)

**Pull request merged**
